import { Hotel, User, RoomType, Room, Guest, Reservation, ServiceRequest, NotificationItem, AuditLog } from '../types';

export const initialHotels: Hotel[] = [
  {
    id: 'hotel-grand-plaza',
    name: 'Grand Plaza Resort',
    slug: 'grand-plaza-resort',
    logo: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=150&auto=format&fit=crop&q=80',
    address: {
      street: 'Av. Beira Mar',
      number: '4500',
      neighborhood: 'Praia do Futuro',
      city: 'Fortaleza',
      state: 'CE',
      zipCode: '60182-000',
      country: 'Brasil',
    },
    phone: '+55 (85) 3456-7800',
    whatsapp: '+55 (85) 99876-5432',
    email: 'contato@grandplaza.com.br',
    checkInTime: '14:00',
    checkOutTime: '12:00',
    breakfast: {
      included: true,
      price: 0,
      hours: '06:30 - 10:30',
      location: 'Restaurante Terraço das Palmeiras (1º Andar)',
    },
    parking: {
      available: true,
      valet: true,
      pricePerDay: 35,
    },
    policies: {
      cancellation: 'Cancelamento gratuito até 48 horas antes do check-in.',
      petsAllowed: true,
      smokingAllowed: false,
      quietHours: '22:00 às 08:00',
    },
    aiPersonality: 'PREMIUM',
    planId: 'PREMIUM',
    status: 'ACTIVE',
    createdAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'hotel-bella-vista',
    name: 'Hotel Bella Vista',
    slug: 'hotel-bella-vista',
    logo: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=150&auto=format&fit=crop&q=80',
    address: {
      street: 'Rua das Hortênsias',
      number: '820',
      neighborhood: 'Planalto',
      city: 'Gramado',
      state: 'RS',
      zipCode: '95670-000',
      country: 'Brasil',
    },
    phone: '+55 (54) 3286-9900',
    whatsapp: '+55 (54) 99123-4567',
    email: 'reservas@hotelbellavista.com.br',
    checkInTime: '15:00',
    checkOutTime: '11:00',
    breakfast: {
      included: true,
      hours: '07:00 - 11:00',
      location: 'Salão Colonial com lareira',
    },
    parking: {
      available: true,
      valet: false,
      pricePerDay: 0,
    },
    policies: {
      cancellation: 'Cancelamento gratuito até 7 dias antes do check-in.',
      petsAllowed: false,
      smokingAllowed: false,
      quietHours: '22:00 às 07:00',
    },
    aiPersonality: 'FRIENDLY',
    planId: 'PRO',
    status: 'ACTIVE',
    createdAt: '2024-02-01T14:30:00Z',
  }
];

export const initialUsers: User[] = [
  {
    id: 'user-super-admin',
    name: 'Super Administrador',
    email: 'superadmin@hotelflow.ai',
    role: 'SUPER_ADMIN',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
    phone: '+55 (11) 99999-0000',
    active: true,
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'user-admin-sarah',
    hotelId: 'hotel-grand-plaza',
    name: 'Sarah Jenkins',
    email: 'admin@grandplaza.com',
    role: 'HOTEL_ADMIN',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=120&auto=format&fit=crop&q=80',
    phone: '+55 (85) 99888-1122',
    active: true,
    createdAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'user-manager-carlos',
    hotelId: 'hotel-grand-plaza',
    name: 'Carlos Mendes',
    email: 'manager@grandplaza.com',
    role: 'MANAGER',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
    phone: '+55 (85) 99777-3344',
    active: true,
    createdAt: '2024-01-20T11:00:00Z',
  },
  {
    id: 'user-reception-ana',
    hotelId: 'hotel-grand-plaza',
    name: 'Ana Paula Santos',
    email: 'reception@grandplaza.com',
    role: 'RECEPTIONIST',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=120&auto=format&fit=crop&q=80',
    phone: '+55 (85) 99666-5566',
    active: true,
    createdAt: '2024-02-01T09:00:00Z',
  },
  {
    id: 'user-staff-lucas',
    hotelId: 'hotel-grand-plaza',
    name: 'Lucas Souza',
    email: 'staff@grandplaza.com',
    role: 'STAFF',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80',
    phone: '+55 (85) 99555-7788',
    active: true,
    createdAt: '2024-02-10T08:00:00Z',
  }
];

export const initialRoomTypes: RoomType[] = [
  {
    id: 'rt-standard-king',
    hotelId: 'hotel-grand-plaza',
    category: 'STANDARD',
    name: 'Standard King',
    description: 'Quarto aconchegante com cama King Size, varanda com vista para o jardim e espaço de trabalho.',
    capacityAdults: 2,
    capacityChildren: 1,
    bedSetup: '1 Cama King Size',
    basePrice: 420,
    promoPrice: 380,
    amenities: ['Wi-Fi 500Mbps', 'Ar-condicionado Split', 'Smart TV 50"', 'Frigobar', 'Cafeteira Nespresso', 'Cofre digital'],
    photos: [
      'https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1590490360182-c33d57733427?w=800&auto=format&fit=crop&q=80',
    ],
  },
  {
    id: 'rt-deluxe-suite',
    hotelId: 'hotel-grand-plaza',
    category: 'DELUXE',
    name: 'Deluxe Suite',
    description: 'Suíte espaçosa com varanda privativa de frente para o mar, banheira de imersão e sala de estar integrada.',
    capacityAdults: 2,
    capacityChildren: 2,
    bedSetup: '1 Cama Super King + Sofá-Cama',
    basePrice: 680,
    promoPrice: 620,
    amenities: ['Vista Panorâmica do Mar', 'Banheira de Hidromassagem', 'Varanda Ampla', 'Wi-Fi 500Mbps', 'Smart TV 65"', 'Roupões Trussardi'],
    photos: [
      'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1591088398332-8a7791972843?w=800&auto=format&fit=crop&q=80',
    ],
  },
  {
    id: 'rt-master-suite',
    hotelId: 'hotel-grand-plaza',
    category: 'SUITE',
    name: 'Master Suite Premium',
    description: 'Elegância e privacidade absoluta. 2 ambientes, closet walk-in, adega climatizada e serviço de mordomo.',
    capacityAdults: 3,
    capacityChildren: 1,
    bedSetup: '1 Cama Super King + 1 Sofá Cama Casal',
    basePrice: 980,
    amenities: ['Serviço de Mordomo', 'Adega Climatizada', 'Café da Manhã no Quarto', 'Amenities L’Occitane', 'Piscina Privativa na Varanda'],
    photos: [
      'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&auto=format&fit=crop&q=80',
    ],
  },
  {
    id: 'rt-family-room',
    hotelId: 'hotel-grand-plaza',
    category: 'FAMILY',
    name: 'Family Suite Garden',
    description: 'Projetada para famílias que buscam conforto máximo com 2 quartos conectados e brinquedoteca privativa.',
    capacityAdults: 4,
    capacityChildren: 2,
    bedSetup: '1 Cama King + 2 Camas Twin',
    basePrice: 850,
    amenities: ['Dois Ambientes Conectados', 'Cozinha Compacta', 'Varanda Térrea com Jardim', 'Smart TV em ambos os quartos'],
    photos: [
      'https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800&auto=format&fit=crop&q=80',
    ],
  },
  {
    id: 'rt-presidential-suite',
    hotelId: 'hotel-grand-plaza',
    category: 'PRESIDENTIAL',
    name: 'Presidential Royal Suite',
    description: 'A experiência máxima em hospitalidade de luxo no último andar com vista 360º, jacuzzi externa e heliponto.',
    capacityAdults: 4,
    capacityChildren: 2,
    bedSetup: '2 Camas Super King',
    basePrice: 2800,
    amenities: ['Jacuzzi Externa Panorâmica', 'Acesso ao Heliponto', 'Chefe de Cozinha Exclusivo', 'Concierge Dedicado 24h', 'Transfers In/Out Inclusos'],
    photos: [
      'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=800&auto=format&fit=crop&q=80',
    ],
  }
];

export const initialRooms: Room[] = [
  // 1st Floor - Family & Standards
  { id: 'room-101', hotelId: 'hotel-grand-plaza', roomTypeId: 'rt-standard-king', roomTypeName: 'Standard King', number: '101', floor: 1, name: 'Quarto 101', status: 'AVAILABLE' },
  { id: 'room-102', hotelId: 'hotel-grand-plaza', roomTypeId: 'rt-standard-king', roomTypeName: 'Standard King', number: '102', floor: 1, name: 'Quarto 102', status: 'OCCUPIED', currentGuestName: 'Felipe Cardoso' },
  { id: 'room-103', hotelId: 'hotel-grand-plaza', roomTypeId: 'rt-standard-king', roomTypeName: 'Standard King', number: '103', floor: 1, name: 'Quarto 103', status: 'CLEANING' },
  { id: 'room-104', hotelId: 'hotel-grand-plaza', roomTypeId: 'rt-standard-king', roomTypeName: 'Standard King', number: '104', floor: 1, name: 'Quarto 104', status: 'AVAILABLE' },
  { id: 'room-108', hotelId: 'hotel-grand-plaza', roomTypeId: 'rt-family-room', roomTypeName: 'Family Suite Garden', number: '108', floor: 1, name: 'Suíte Família 108', status: 'OCCUPIED', currentGuestName: 'Beatriz Santos' },
  { id: 'room-112', hotelId: 'hotel-grand-plaza', roomTypeId: 'rt-standard-king', roomTypeName: 'Standard King', number: '112', floor: 1, name: 'Quarto 112', status: 'MAINTENANCE', notes: 'Manutenção no ar condicionado' },

  // 2nd Floor - Standards & Deluxes
  { id: 'room-201', hotelId: 'hotel-grand-plaza', roomTypeId: 'rt-standard-king', roomTypeName: 'Standard King', number: '201', floor: 2, name: 'Quarto 201', status: 'AVAILABLE' },
  { id: 'room-204', hotelId: 'hotel-grand-plaza', roomTypeId: 'rt-standard-king', roomTypeName: 'Standard King', number: '204', floor: 2, name: 'Quarto 204', status: 'OCCUPIED', currentGuestName: 'Camila Nogueira' },
  { id: 'room-215', hotelId: 'hotel-grand-plaza', roomTypeId: 'rt-standard-king', roomTypeName: 'Standard King', number: '215', floor: 2, name: 'Quarto 215', status: 'OCCUPIED', currentGuestName: 'John Smith' },
  { id: 'room-216', hotelId: 'hotel-grand-plaza', roomTypeId: 'rt-deluxe-suite', roomTypeName: 'Deluxe Suite', number: '216', floor: 2, name: 'Suíte Deluxe 216', status: 'OCCUPIED', currentGuestName: 'Rodrigo Faro' },
  { id: 'room-218', hotelId: 'hotel-grand-plaza', roomTypeId: 'rt-deluxe-suite', roomTypeName: 'Deluxe Suite', number: '218', floor: 2, name: 'Suíte Deluxe 218', status: 'RESERVED' },

  // 3rd Floor - Deluxes & Masters
  { id: 'room-301', hotelId: 'hotel-grand-plaza', roomTypeId: 'rt-master-suite', roomTypeName: 'Master Suite Premium', number: '301', floor: 3, name: 'Master Suite 301', status: 'RESERVED', notes: 'Hóspede VIP chegando às 15:30' },
  { id: 'room-305', hotelId: 'hotel-grand-plaza', roomTypeId: 'rt-deluxe-suite', roomTypeName: 'Deluxe Suite', number: '305', floor: 3, name: 'Suíte Deluxe 305', status: 'OCCUPIED', currentGuestName: 'Marcio Azevedo' },
  { id: 'room-308', hotelId: 'hotel-grand-plaza', roomTypeId: 'rt-deluxe-suite', roomTypeName: 'Deluxe Suite', number: '308', floor: 3, name: 'Suíte Deluxe 308', status: 'OCCUPIED', currentGuestName: 'Juliana Paes' },

  // 4th Floor - High Tier Deluxes & Master
  { id: 'room-401', hotelId: 'hotel-grand-plaza', roomTypeId: 'rt-deluxe-suite', roomTypeName: 'Deluxe Suite', number: '401', floor: 4, name: 'Suíte Deluxe 401', status: 'AVAILABLE' },
  { id: 'room-402', hotelId: 'hotel-grand-plaza', roomTypeId: 'rt-deluxe-suite', roomTypeName: 'Deluxe Suite', number: '402', floor: 4, name: 'Suíte Deluxe 402', status: 'RESERVED', notes: 'Check-in hoje: Maria Rodriguez' },
  { id: 'room-405', hotelId: 'hotel-grand-plaza', roomTypeId: 'rt-master-suite', roomTypeName: 'Master Suite Premium', number: '405', floor: 4, name: 'Master Suite 405', status: 'OCCUPIED', currentGuestName: 'Eduardo Guimarães' },

  // 5th Floor - Penthouse & Presidential
  { id: 'room-501', hotelId: 'hotel-grand-plaza', roomTypeId: 'rt-presidential-suite', roomTypeName: 'Presidential Royal Suite', number: '501', floor: 5, name: 'Royal Presidential 501', status: 'RESERVED', notes: 'Check-in: Elena Rostova' },
];

export const initialGuests: Guest[] = [
  {
    id: 'guest-1',
    hotelId: 'hotel-grand-plaza',
    name: 'Maria Rodriguez',
    email: 'maria.rodriguez@example.com',
    phone: '+55 (11) 98765-4321',
    document: '348.912.871-04',
    country: 'Brasil',
    tags: ['VIP', 'FREQUENT'],
    notes: 'Prefere travesseiros de pluma e água com gás no quarto.',
    totalSpent: 12450,
    staysCount: 4,
    ratingAverage: 5,
    createdAt: '2023-11-10T10:00:00Z',
  },
  {
    id: 'guest-2',
    hotelId: 'hotel-grand-plaza',
    name: 'John Smith',
    email: 'john.smith@ukcorp.com',
    phone: '+44 7911 123456',
    document: 'GB89412904',
    country: 'Reino Unido',
    tags: ['CORPORATE', 'VIP'],
    notes: 'Viajante corporativo frequente. Precisa de nota fiscal com CNPJ internacional.',
    totalSpent: 28900,
    staysCount: 7,
    ratingAverage: 4.8,
    createdAt: '2023-08-20T14:00:00Z',
  },
  {
    id: 'guest-3',
    hotelId: 'hotel-grand-plaza',
    name: 'Lucas Alcantara',
    email: 'lucas.alcantara@techventures.io',
    phone: '+55 (21) 99123-8899',
    document: '112.458.790-33',
    country: 'Brasil',
    tags: ['VIP', 'BIRTHDAY'],
    notes: 'Comemorando aniversário de casamento.',
    totalSpent: 8900,
    staysCount: 2,
    ratingAverage: 5,
    createdAt: '2024-01-05T12:00:00Z',
  },
  {
    id: 'guest-4',
    hotelId: 'hotel-grand-plaza',
    name: 'Beatriz Santos',
    email: 'beatriz.santos@gmail.com',
    phone: '+55 (85) 98111-2233',
    document: '654.123.987-11',
    country: 'Brasil',
    tags: ['FAMILY'],
    notes: 'Viajando com 2 crianças pequenas.',
    totalSpent: 4250,
    staysCount: 1,
    ratingAverage: 5,
    createdAt: '2024-03-01T08:00:00Z',
  },
  {
    id: 'guest-5',
    hotelId: 'hotel-grand-plaza',
    name: 'Elena Rostova',
    email: 'elena.rostova@monaco-yachts.com',
    phone: '+33 6 12 34 56 78',
    document: 'FR90123847',
    country: 'França',
    tags: ['VIP'],
    notes: 'Solicitou champanhe Dom Pérignon no check-in.',
    totalSpent: 35000,
    staysCount: 3,
    ratingAverage: 5,
    createdAt: '2023-12-15T19:00:00Z',
  }
];

export const initialReservations: Reservation[] = [
  {
    id: 'res-101',
    code: 'RES-8921',
    hotelId: 'hotel-grand-plaza',
    guestId: 'guest-1',
    guestName: 'Maria Rodriguez',
    guestEmail: 'maria.rodriguez@example.com',
    guestPhone: '+55 (11) 98765-4321',
    guestDocument: '348.912.871-04',
    roomId: 'room-402',
    roomNumber: '402',
    roomTypeName: 'Deluxe Suite (402)',
    checkInDate: '2026-08-16',
    checkOutDate: '2026-08-19',
    checkInTimeEstimated: '14:00',
    adults: 2,
    children: 0,
    dailyRate: 680,
    nights: 3,
    subtotal: 2040,
    discount: 100,
    extraServicesTotal: 180,
    extraServices: [
      { id: 'srv-1', name: 'Garrafa Espumante Brut', price: 180, quantity: 1 }
    ],
    totalAmount: 2120,
    status: 'PENDING',
    paymentStatus: 'PAID',
    paymentMethod: 'PIX',
    origin: 'WHATSAPP_AI',
    notes: 'Reserva realizada via WhatsApp IA com confirmação instantânea de PIX.',
    createdAt: '2026-08-15T16:20:00Z',
  },
  {
    id: 'res-102',
    code: 'RES-8922',
    hotelId: 'hotel-grand-plaza',
    guestId: 'guest-2',
    guestName: 'John Smith',
    guestEmail: 'john.smith@ukcorp.com',
    guestPhone: '+44 7911 123456',
    guestDocument: 'GB89412904',
    roomId: 'room-215',
    roomNumber: '215',
    roomTypeName: 'Standard King (215)',
    checkInDate: '2026-08-16',
    checkOutDate: '2026-08-21',
    checkInTimeEstimated: '11:30',
    actualCheckIn: '2026-08-16T11:42:00Z',
    adults: 1,
    children: 0,
    dailyRate: 420,
    nights: 5,
    subtotal: 2100,
    discount: 0,
    extraServicesTotal: 250,
    extraServices: [
      { id: 'srv-2', name: 'Transfer Executivo Aeroporto', price: 180, quantity: 1 },
      { id: 'srv-3', name: 'Lavanderia Express', price: 70, quantity: 1 },
    ],
    totalAmount: 2350,
    status: 'CHECKED_IN',
    paymentStatus: 'PAID',
    paymentMethod: 'CREDIT_CARD',
    origin: 'DIRECT_WEBSITE',
    notes: 'Check-in adiantado autorizado.',
    createdAt: '2026-08-10T14:15:00Z',
  },
  {
    id: 'res-103',
    code: 'RES-8923',
    hotelId: 'hotel-grand-plaza',
    guestId: 'guest-3',
    guestName: 'Lucas Alcantara',
    guestEmail: 'lucas.alcantara@techventures.io',
    guestPhone: '+55 (21) 99123-8899',
    guestDocument: '112.458.790-33',
    roomId: 'room-301',
    roomNumber: '301',
    roomTypeName: 'Master Suite Premium (301)',
    checkInDate: '2026-08-16',
    checkOutDate: '2026-08-18',
    checkInTimeEstimated: '15:30',
    adults: 2,
    children: 0,
    dailyRate: 980,
    nights: 2,
    subtotal: 1960,
    discount: 0,
    extraServicesTotal: 320,
    extraServices: [
      { id: 'srv-4', name: 'Decoração Romântica com Pétalas e Velas', price: 250, quantity: 1 },
      { id: 'srv-5', name: 'Café da Manhã Especial no Quarto', price: 70, quantity: 1 }
    ],
    totalAmount: 2280,
    status: 'PENDING',
    paymentStatus: 'PAID',
    paymentMethod: 'CREDIT_CARD',
    origin: 'WHATSAPP_AI',
    notes: 'Cliente fez upsell do pacote romântico diretamente com a IA.',
    createdAt: '2026-08-14T20:00:00Z',
  },
  {
    id: 'res-104',
    code: 'RES-8924',
    hotelId: 'hotel-grand-plaza',
    guestId: 'guest-4',
    guestName: 'Beatriz Santos',
    guestEmail: 'beatriz.santos@gmail.com',
    guestPhone: '+55 (85) 98111-2233',
    guestDocument: '654.123.987-11',
    roomId: 'room-108',
    roomNumber: '108',
    roomTypeName: 'Family Suite Garden (108)',
    checkInDate: '2026-08-16',
    checkOutDate: '2026-08-20',
    checkInTimeEstimated: '13:00',
    actualCheckIn: '2026-08-16T13:10:00Z',
    adults: 2,
    children: 2,
    dailyRate: 850,
    nights: 4,
    subtotal: 3400,
    discount: 200,
    extraServicesTotal: 120,
    extraServices: [
      { id: 'srv-6', name: 'Berço e Kit Kids', price: 0, quantity: 1 },
      { id: 'srv-7', name: 'Late Check-out 15h', price: 120, quantity: 1 }
    ],
    totalAmount: 3320,
    status: 'CHECKED_IN',
    paymentStatus: 'PAID',
    paymentMethod: 'PIX',
    origin: 'DIRECT_WEBSITE',
    createdAt: '2026-08-12T09:40:00Z',
  },
  {
    id: 'res-105',
    code: 'RES-8925',
    hotelId: 'hotel-grand-plaza',
    guestId: 'guest-5',
    guestName: 'Elena Rostova',
    guestEmail: 'elena.rostova@monaco-yachts.com',
    guestPhone: '+33 6 12 34 56 78',
    guestDocument: 'FR90123847',
    roomId: 'room-501',
    roomNumber: '501',
    roomTypeName: 'Presidential Royal Suite (501)',
    checkInDate: '2026-08-16',
    checkOutDate: '2026-08-22',
    checkInTimeEstimated: '16:00',
    adults: 2,
    children: 0,
    dailyRate: 2800,
    nights: 6,
    subtotal: 16800,
    discount: 0,
    extraServicesTotal: 1500,
    extraServices: [
      { id: 'srv-8', name: 'Heliponto Recepção VIP', price: 800, quantity: 1 },
      { id: 'srv-9', name: 'Jantar Degustação Harmonizado', price: 700, quantity: 1 }
    ],
    totalAmount: 18300,
    status: 'CONFIRMED',
    paymentStatus: 'PAID',
    paymentMethod: 'CREDIT_CARD',
    origin: 'WHATSAPP_AI',
    notes: 'Reserva VIP de alto valor via assistente executivo.',
    createdAt: '2026-08-11T18:00:00Z',
  }
];

export const initialServiceRequests: ServiceRequest[] = [
  {
    id: 'req-1',
    hotelId: 'hotel-grand-plaza',
    reservationId: 'res-101',
    roomNumber: '305',
    guestName: 'Marcio Azevedo',
    type: 'TOWELS',
    title: 'Extra Towels - Room 305',
    description: 'Hóspede solicitou 2 toalhas de banho extras e 1 tapete.',
    priority: 'NORMAL',
    status: 'PENDING',
    requestedAt: 'Há 10 minutos',
  },
  {
    id: 'req-2',
    hotelId: 'hotel-grand-plaza',
    roomNumber: '112',
    guestName: 'Recepção / Governança',
    type: 'MAINTENANCE',
    title: 'AC Maintenance - Room 112',
    description: 'Ar condicionado apresentando ruído no condensador.',
    priority: 'HIGH',
    status: 'PENDING',
    requestedAt: 'Há 45 minutos',
  },
  {
    id: 'req-3',
    hotelId: 'hotel-grand-plaza',
    reservationId: 'res-101',
    roomNumber: '402',
    guestName: 'Maria Rodriguez',
    type: 'ROOM_SERVICE',
    title: 'Garrafa de Espumante e Taças - Room 402',
    description: 'Colocar balde com gelo e espumante antes da chegada.',
    priority: 'NORMAL',
    status: 'IN_PROGRESS',
    assignedStaffName: 'Lucas Souza',
    requestedAt: 'Há 25 minutos',
  },
  {
    id: 'req-4',
    hotelId: 'hotel-grand-plaza',
    reservationId: 'res-102',
    roomNumber: '215',
    guestName: 'John Smith',
    type: 'PILLOW_BLANKET',
    title: 'Travesseiros Extra Firmes - Room 215',
    description: 'Entregar 2 travesseiros ortopédicos no quarto.',
    priority: 'LOW',
    status: 'COMPLETED',
    assignedStaffName: 'Lucas Souza',
    requestedAt: 'Há 2 horas',
    completedAt: 'Há 1 hora',
  }
];

export const initialNotifications: NotificationItem[] = [
  {
    id: 'notif-1',
    hotelId: 'hotel-grand-plaza',
    title: 'Nova Reserva Confirmada via WhatsApp IA',
    message: 'Maria Rodriguez reservou a Deluxe Suite 402 por 3 diárias (R$ 2.120,00)',
    type: 'RESERVATION',
    read: false,
    timestamp: 'Há 8 minutos',
  },
  {
    id: 'notif-2',
    hotelId: 'hotel-grand-plaza',
    title: 'Pagamento PIX Aprovado Instantaneamente',
    message: 'R$ 2.120,00 recebidos referente à reserva RES-8921',
    type: 'PAYMENT',
    read: false,
    timestamp: 'Há 12 minutos',
  },
  {
    id: 'notif-3',
    hotelId: 'hotel-grand-plaza',
    title: 'Nova Solicitação do Quarto 305',
    message: 'Toalhas extras solicitadas pelo portal do hóspede',
    type: 'REQUEST',
    read: false,
    timestamp: 'Há 15 minutos',
  },
  {
    id: 'notif-4',
    hotelId: 'hotel-grand-plaza',
    title: 'Check-in Realizado: Quarto 215',
    message: 'John Smith realizou o check-in na recepção',
    type: 'SYSTEM',
    read: true,
    timestamp: 'Há 2 horas',
  }
];

export const initialAuditLogs: AuditLog[] = [
  {
    id: 'log-1',
    hotelId: 'hotel-grand-plaza',
    userId: 'user-admin-sarah',
    userName: 'Sarah Jenkins',
    action: 'CHECK_IN_PROCESSED',
    target: 'Reserva RES-8922 (Quarto 215)',
    details: 'Check-in presencial confirmado e chave digital liberada para John Smith.',
    timestamp: '2026-08-16 11:42:15',
  },
  {
    id: 'log-2',
    hotelId: 'hotel-grand-plaza',
    userId: 'system-ai',
    userName: 'HotelFlow AI Engine',
    action: 'RESERVATION_CREATED',
    target: 'Reserva RES-8921',
    details: 'Reserva autônoma criada via WhatsApp com verificação de disponibilidade em tempo real.',
    timestamp: '2026-08-16 11:20:04',
  },
  {
    id: 'log-3',
    hotelId: 'hotel-grand-plaza',
    userId: 'system-ai',
    userName: 'Payment Gateway Adapter',
    action: 'PAYMENT_CONFIRMED',
    target: 'PIX R$ 2.120,00',
    details: 'Comprovante verificado e status alterado para PAID.',
    timestamp: '2026-08-16 11:21:10',
  },
  {
    id: 'log-4',
    hotelId: 'hotel-grand-plaza',
    userId: 'user-reception-ana',
    userName: 'Ana Paula Santos',
    action: 'SERVICE_REQUEST_ASSIGNED',
    target: 'Solicitação #req-3',
    details: 'Atribuído para funcionário Lucas Souza.',
    timestamp: '2026-08-16 11:35:00',
  }
];
